# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sourcegraph < Formula
  desc "Code intelligence and search"
  homepage "https://github.com/sourcegraph/sourcegraph"
  version "2023.03.23+207954.83b0a7"
  license "Sourcegraph Enterprise License (portions licensed under Apache 2)"

  depends_on "git"
  depends_on "sourcegraph/src-cli/src-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/sourcegraph-app-releases/2023.03.23+207954.83b0a7/sourcegraph_2023.03.23+207954.83b0a7_darwin_amd64.zip"
      sha256 "30fbc1700b8519626a8a4bfa70621165fe25292eee84e7daf4b0566cae659635"

      def install
        bin.install "sourcegraph"
      end
    end
    if Hardware::CPU.arm?
      url "https://storage.googleapis.com/sourcegraph-app-releases/2023.03.23+207954.83b0a7/sourcegraph_2023.03.23+207954.83b0a7_darwin_arm64.zip"
      sha256 "ec82937f0c03da5041737f096a2119d35ef0149dc218efdf3718511574c48db9"

      def install
        bin.install "sourcegraph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/sourcegraph-app-releases/2023.03.23+207954.83b0a7/sourcegraph_2023.03.23+207954.83b0a7_linux_amd64.zip"
      sha256 "bf8736dc64d8a8754406a41f49466fb20a34d3f46c29b04e22e2fd6ff1b6f4e7"

      def install
        bin.install "sourcegraph"
      end
    end
  end

  test do
    system "#{bin}/sourcegraph --help"
  end
end
