# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sourcegraph < Formula
  desc "Code intelligence and search"
  homepage "https://github.com/sourcegraph/sourcegraph"
  version "2023.03.23+207861.6d0f38"
  license "Sourcegraph Enterprise License (portions licensed under Apache 2)"

  depends_on "git"
  depends_on "sourcegraph/src-cli/src-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/sourcegraph-app-releases/2023.03.23+207861.6d0f38/sourcegraph_2023.03.23+207861.6d0f38_darwin_amd64.zip"
      sha256 "961ed22f16ffe87d87eb24aae26b18d070f7953a0b25542061505df1619cbbf3"

      def install
        bin.install "sourcegraph"
      end
    end
    if Hardware::CPU.arm?
      url "https://storage.googleapis.com/sourcegraph-app-releases/2023.03.23+207861.6d0f38/sourcegraph_2023.03.23+207861.6d0f38_darwin_arm64.zip"
      sha256 "1af43e8fed89b268bb0517f71f661ad743f96f5f35ae563eb167b6cf19f45ade"

      def install
        bin.install "sourcegraph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/sourcegraph-app-releases/2023.03.23+207861.6d0f38/sourcegraph_2023.03.23+207861.6d0f38_linux_amd64.zip"
      sha256 "9b1c581d5e957a08b6447071fd9d0ce51b13381cad293d07288c8d688cb7e233"

      def install
        bin.install "sourcegraph"
      end
    end
  end

  test do
    system "#{bin}/sourcegraph --help"
  end
end
